version: '3'

services:
  llm-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      MODEL_PATH: "/app"
      RATE_LIMIT: "1000 per minute"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"